#cmakedefine01 WSD_HAVE_SSL

#cmakedefine01 WSD_HAVE_UBUS
#cmakedefine01 WSD_HAVE_UBUSPROXY

#cmakedefine01 WSD_HAVE_DBUS
#cmakedefine WSD_DBUS_OBJECTS_PATH "@WSD_DBUS_OBJECTS_PATH@"

#cmakedefine01 WSD_USER_BLACKLIST_OLD

